<?php
namespace App\Common;

class JanusConstants
{
    // ./janus-gateway/src/events/eventhandler.h
    const JANUS_EVENT_TYPE_NONE = 0;
    const JANUS_EVENT_TYPE_SESSION = 1 << 0;
    const JANUS_EVENT_TYPE_HANDLE = 1 << 1;
    const JANUS_EVENT_TYPE_EXTERNAL = 1 << 2;
    const JANUS_EVENT_TYPE_JSEP = 1 << 3;
    const JANUS_EVENT_TYPE_WEBRTC = 1 << 4;
    const JANUS_EVENT_TYPE_MEDIA = 1 << 5;
    const JANUS_EVENT_TYPE_PLUGIN = 1 << 6;
    const JANUS_EVENT_TYPE_TRANSPORT = 1 << 7;
    const JANUS_EVENT_TYPE_CORE = 1 << 8;
    const JANUS_EVENT_TYPE_ALL = 0xffffffff;

    // ./janus-gateway/src/plugins/janus_textroom.c
    const JANUS_TEXTROOM_ERROR_NO_MESSAGE = 411;
    const JANUS_TEXTROOM_ERROR_INVALID_JSON = 412;
    const JANUS_TEXTROOM_ERROR_MISSING_ELEMENT = 413;
    const JANUS_TEXTROOM_ERROR_INVALID_ELEMENT = 414;
    const JANUS_TEXTROOM_ERROR_INVALID_REQUEST = 415;
    const JANUS_TEXTROOM_ERROR_ALREADY_SETUP = 416;
    const JANUS_TEXTROOM_ERROR_NO_SUCH_ROOM = 417;
    const JANUS_TEXTROOM_ERROR_ROOM_EXISTS = 418;
    const JANUS_TEXTROOM_ERROR_UNAUTHORIZED = 419;
    const JANUS_TEXTROOM_ERROR_USERNAME_EXISTS = 420;
    const JANUS_TEXTROOM_ERROR_ALREADY_IN_ROOM = 421;
    const JANUS_TEXTROOM_ERROR_NOT_IN_ROOM = 422;
    const JANUS_TEXTROOM_ERROR_NO_SUCH_USER = 423;
    const JANUS_TEXTROOM_ERROR_UNKNOWN_ERROR = 499;
}

